# Generated by Django 5.0.3 on 2024-04-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_remove_message_chat_room_remove_message_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='post',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='uuid',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
